[package]
name = "bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[[bin]]
name = "bridge"
path = "src/main.rs"

[dependencies]
# bridge
# http = { path = "../../crates/http" }

# external
clap = { version = "4.5.4", features = ["derive"] }
